apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"aws.cdk.eks/prune-c848977de96d6511c4f2204d55873d90dd35bb92a2":""},"name":"karpenter-sqs-subscriber","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"karpenter-sqs-subscriber"}},"template":{"metadata":{"labels":{"app":"karpenter-sqs-subscriber"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"zonal-autoshift-karpenter","operator":"In","values":["karpenter"]}]}]}},"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"app":"karpenter-sqs-subscriber"}},"topologyKey":"topology.kubernetes.io/zone"}]}},"automountServiceAccountToken":true,"containers":[{"env":[{"name":"AWS_REGION","value":"us-west-2"},{"name":"AWS_ACCOUNT_ID","value":"491645480735"},{"name":"CLUSTER_NAME","value":"EKSClusterStack-cluster"},{"name":"SQS_QUEUE_URL","value":"https://sqs.us-west-2.amazonaws.com/491645480735/zonal-shift"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"491645480735.dkr.ecr.us-west-2.amazonaws.com/zonalautoshiftkarpenter","imagePullPolicy":"Always","name":"karpenter-sqs-subscriber","resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":[],"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true,"runAsUser":10000,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":[{"mountPath":"/var/log","name":"log-volume"}]}],"dnsConfig":{"nameservers":["8.8.8.8"]},"securityContext":{"fsGroup":10000,"runAsGroup":10000,"runAsNonRoot":true,"runAsUser":10000},"serviceAccountName":"karpenter-sqs-subscriber","volumes":[{"emptyDir":{"medium":"Memory"},"name":"log-volume"}]}}}}
  creationTimestamp: "2025-12-09T07:22:24Z"
  generation: 1
  labels:
    aws.cdk.eks/prune-c848977de96d6511c4f2204d55873d90dd35bb92a2: ""
  name: karpenter-sqs-subscriber
  namespace: default
  resourceVersion: "693951"
  uid: a74ab9c9-dbbc-4797-95e0-e5695dcd16b9
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: karpenter-sqs-subscriber
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: karpenter-sqs-subscriber
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zonal-autoshift-karpenter
                    operator: In
                    values:
                      - karpenter
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: karpenter-sqs-subscriber
              topologyKey: topology.kubernetes.io/zone
      automountServiceAccountToken: true
      containers:
        - env:
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_ACCOUNT_ID
              value: "491645480735"
            - name: CLUSTER_NAME
              value: EKSClusterStack-cluster
            - name: SQS_QUEUE_URL
              value: https://sqs.us-west-2.amazonaws.com/491645480735/zonal-shift
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: 491645480735.dkr.ecr.us-west-2.amazonaws.com/zonalautoshiftkarpenter
          imagePullPolicy: Always
          name: karpenter-sqs-subscriber
          # Uncomment the lines below to enable the do-not-disrupt feature
          command: ["/sns-subscriber"]
          args: ["--enable-do-not-disrupt"]
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log
              name: log-volume
      dnsConfig:
        nameservers:
          - 8.8.8.8
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
        runAsGroup: 10000
        runAsNonRoot: true
        runAsUser: 10000
      serviceAccount: karpenter-sqs-subscriber
      serviceAccountName: karpenter-sqs-subscriber
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir:
            medium: Memory
          name: log-volume
